# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-31 20:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_source', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Friend',
                'verbose_name_plural': 'Account Friends',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocking', models.BooleanField(default=False)),
                ('muting', models.BooleanField(default=False)),
                ('marked_as_spam', models.BooleanField(default=False)),
                ('notifications_enabled', models.BooleanField(default=False)),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_source', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Relationship',
                'verbose_name_plural': 'Account Relationships',
            },
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together=set([('source_user', 'target_user')]),
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set([('source_user', 'target_user')]),
        ),
    ]
