# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-22 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='type',
            new_name='msg_type',
        ),
    ]
